# Generated by Django 6.0.7 on 2026-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmessage_is_unlocked_groupmessage_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
